#!/bin/sh

function ip_addr()
{
	/sbin/ifconfig eth0 | grep -i mask | awk '{print $2}' | cut -f2 -d':'
}

function kmsg()
{
	echo "$1"
}

function banner()
{
kmsg ""
kmsg "       _   __                  ____  ______   ___________
kmsg "      / | / /___ _____  ____  / __ \\/ ____/  /_  __/ ___/
kmsg "     /  |/ / __ `/ __ \\/ __ \\/ /_/ / /  ______/ / / __ \\ 
kmsg "    / /|  / /_/ / / / / /_/ / ____/ /__/_____/ / / /_/ / 
kmsg "   /_/ |_/\\__,_/_/ /_/\\____/_/    \\____/    /_/  \\____/  
kmsg ""

kmsg "   $(dmesg -t | grep "Machine model")"
kmsg "   CPU cores: $(nproc --all)"
kmsg "   $(dmesg -t | grep "Memory:" | cut -f1 -d'(')"
kmsg "   Kernel: $(uname -r) $(uname -m)"
kmsg "   IP Address: $(ip_addr)"
kmsg ""
}

case "$1" in
  start)
	sleep 3
	banner
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
